import { UIElement } from "./UIElement";
import { Vec2 } from "../math/Vec2";
import { Margin } from "../math/Margin";
export declare class Image extends UIElement {
    protected _src: string;
    protected _color: number;
    protected _scaleByTile: boolean;
    protected _scale9Grid: Margin;
    protected _textureScale: Vec2;
    protected _tileGridIndice: number;
    protected _fillMethod: number;
    protected _fillOrigin: number;
    protected _fillClockwise: boolean;
    protected _fillAmount: number;
    private _timerID_1;
    constructor();
    get src(): string;
    set src(value: string);
    get color(): number;
    set color(value: number);
    get textureScale(): Vec2;
    set textureScale(value: Vec2);
    get scale9Grid(): Margin;
    set scale9Grid(value: Margin);
    get scaleByTile(): boolean;
    set scaleByTile(value: boolean);
    get tileGridIndice(): number;
    set tileGridIndice(value: number);
    get fillMethod(): number;
    set fillMethod(value: number);
    get fillOrigin(): number;
    set fillOrigin(value: number);
    get fillClockwise(): boolean;
    set fillClockwise(value: boolean);
    get fillAmount(): number;
    set fillAmount(value: number);
    protected onSizeChanged(): void;
    protected updateFill(): void;
    protected updateFilters(): void;
    protected refresh(): void;
}
