import { EventDispatcher } from "../event/EventDispatcher";
import { GComponent } from "./GComponent";
import { ByteBuffer } from "../utils/ByteBuffer";
export declare class Controller extends EventDispatcher {
    private _selectedIndex;
    private _previousIndex;
    private _pageIds;
    private _pageNames;
    private _actions?;
    name: string;
    parent: GComponent;
    autoRadioGroupDepth?: boolean;
    changing: boolean;
    constructor();
    dispose(): void;
    get selectedIndex(): number;
    set selectedIndex(value: number);
    setSelectedIndex(value: number): void;
    get previousIndex(): number;
    get selectedPage(): string;
    set selectedPage(val: string);
    setSelectedPage(value: string): void;
    get previousPage(): string;
    get pageCount(): number;
    getPageName(index: number): string;
    addPage(name?: string): void;
    addPageAt(name?: string, index?: number): void;
    removePage(name: string): void;
    removePageAt(index: number): void;
    clearPages(): void;
    hasPage(aName: string): boolean;
    getPageIndexById(aId: string): number;
    getPageIdByName(aName: string): string;
    getPageNameById(aId: string): string;
    getPageId(index: number): string;
    get selectedPageId(): string;
    set selectedPageId(val: string);
    set oppositePageId(val: string);
    get previousPageId(): string;
    runActions(): void;
    setup(buffer: ByteBuffer): void;
}
