import { Event } from "../event/Event";
import { Vec2 } from "../math/Vec2";
import { ByteBuffer } from "../utils/ByteBuffer";
import { Controller } from "./Controller";
import { AlignType, VertAlignType } from "./FieldTypes";
import { GComponent } from "./GComponent";
import { GObject } from "./GObject";
import { GObjectPool } from "./GObjectPool";
export type ListItemRenderer = (index: number, item: GObject) => void;
export declare class GList extends GComponent {
    itemRenderer: ListItemRenderer;
    itemProvider: (index: number) => string;
    scrollItemToViewOnClick: boolean;
    foldInvisibleItems: boolean;
    private _layout;
    private _lineCount;
    private _columnCount;
    private _lineGap;
    private _columnGap;
    private _defaultItem;
    private _autoResizeItem;
    private _selectionMode;
    private _align;
    private _valign;
    private _selectionController?;
    private _lastSelectedIndex;
    private _triggerFocusEvents?;
    private _keySelectEvent?;
    private _pool;
    private _virtual;
    private _loop;
    private _numItems;
    private _realNumItems;
    private _firstIndex;
    private _curLineItemCount;
    private _curLineItemCount2;
    private _itemSize;
    private _virtualListChanged;
    private _virtualItems;
    private _eventLocked;
    private itemInfoVer;
    constructor();
    dispose(): void;
    get layout(): number;
    set layout(value: number);
    get lineCount(): number;
    set lineCount(value: number);
    get columnCount(): number;
    set columnCount(value: number);
    get lineGap(): number;
    set lineGap(value: number);
    get columnGap(): number;
    set columnGap(value: number);
    get align(): AlignType;
    set align(value: AlignType);
    get verticalAlign(): VertAlignType;
    set verticalAlign(value: VertAlignType);
    get virtualItemSize(): Vec2;
    set virtualItemSize(value: Vec2);
    get defaultItem(): string;
    set defaultItem(val: string);
    get autoResizeItem(): boolean;
    set autoResizeItem(value: boolean);
    get selectionMode(): number;
    set selectionMode(value: number);
    get selectionController(): Controller;
    set selectionController(value: Controller);
    get itemPool(): GObjectPool;
    getFromPool(url?: string): GObject;
    returnToPool(obj: GObject): void;
    setDefaultItemSize(sizeX: number, sizeY: number): void;
    addChildAt(child: GObject, index: number): GObject;
    addItem(url?: string): GObject;
    addItemFromPool(url?: string): GObject;
    removeChildAt(index: number, dispose?: boolean): GObject;
    removeChildToPoolAt(index: number): void;
    removeChildToPool(child: GObject): void;
    removeChildrenToPool(beginIndex?: number, endIndex?: number): void;
    get selectedIndex(): number;
    set selectedIndex(value: number);
    getSelection(result?: number[]): number[];
    addSelection(index: number, scrollItToView?: boolean): void;
    removeSelection(index: number): void;
    clearSelection(): void;
    private clearSelectionExcept;
    selectAll(): void;
    selectNone(): void;
    selectReverse(): void;
    enableSelectionFocusEvents(enabled: boolean): void;
    private notifySelection;
    enableArrowKeyNavigation(enabled: boolean, keySelectEvent?: string): void;
    private __keydown;
    handleArrowKey(dir: number): number;
    private __clickItem;
    protected dispatchItemEvent(item: GObject, evt: Event): void;
    private setSelectionOnEvent;
    resizeToFit(itemCount?: number, minSize?: number): void;
    getMaxItemWidth(): number;
    protected handleSizeChanged(): void;
    handleControllerChanged(c: Controller): void;
    private updateSelectionController;
    private shouldSnapToNext;
    getSnappingPositionWithDir(xValue: number, yValue: number, xDir: number, yDir: number, resultPoint?: Vec2): Vec2;
    scrollToView(index: number, ani?: boolean, setFirst?: boolean): void;
    get touchItem(): GObject | null;
    getFirstChildInView(): number;
    childIndexToItemIndex(index: number): number;
    itemIndexToChildIndex(index: number): number;
    setVirtual(): void;
    /**
     * Set the list to be virtual list, and has loop behavior.
     */
    setVirtualAndLoop(): void;
    private _setVirtual;
    get numItems(): number;
    set numItems(value: number);
    refreshVirtualList(): void;
    private checkVirtualList;
    private setVirtualListChangedFlag;
    private _refreshVirtualList;
    private __scrolled;
    private getIndexOnPos1;
    private getIndexOnPos2;
    private getIndexOnPos3;
    private handleScroll;
    private handleScroll1;
    private handleScroll2;
    private handleScroll3;
    private handleArchOrder1;
    private handleArchOrder2;
    private handleAlign;
    protected updateBounds(): void;
    setup_beforeAdd(buffer: ByteBuffer, beginPos: number): void;
    protected readItems(buffer: ByteBuffer): void;
    protected setupItem(buffer: ByteBuffer, obj: GObject): void;
    setup_afterAdd(buffer: ByteBuffer, beginPos: number): void;
}
