import { PopupDirection } from "./FieldTypes";
import { GComponent } from "./GComponent";
import { GObject } from "./GObject";
import { GWindow } from "./GWindow";
import { Vec2 } from "../math/Vec2";
import { Stage } from "../core/Stage";
export declare class GRoot extends GComponent {
    private _modalLayer;
    private _popupStack;
    private _justClosedPopups;
    private _modalWaitPane;
    private _tooltipWin;
    private _defaultTooltipWin;
    protected _element: Stage;
    static get inst(): GRoot;
    static getInst(obj: GObject): GRoot;
    constructor(ownerWindow?: Window);
    protected createElement(): void;
    get element(): Stage;
    get pointerPos(): Vec2;
    get touchScreen(): boolean;
    get touchCount(): number;
    getPointerPos(pointerId?: number, ret?: Vec2): Vec2;
    get touchTarget(): GObject | null;
    get focusedObj(): GObject | null;
    showWindow(win: GWindow): void;
    hideWindow(win: GWindow): void;
    hideWindowImmediately(win: GWindow): void;
    bringToFront(win: GWindow): void;
    showModalWait(msg?: string): void;
    closeModalWait(): void;
    closeAllExceptModals(): void;
    closeAllWindows(): void;
    getTopWindow(): GWindow;
    get modalLayer(): GObject;
    get hasModalWindow(): boolean;
    get modalWaiting(): boolean;
    showPopup(popup: GObject, target?: GObject, dir?: PopupDirection): void;
    togglePopup(popup: GObject, target?: GObject, dir?: PopupDirection): void;
    hidePopup(popup?: GObject): void;
    get hasAnyPopup(): boolean;
    private closePopup;
    showTooltips(msg: string): void;
    showTooltipsWin(tooltipWin: GObject, xx?: number, yy?: number): void;
    hideTooltips(): void;
    static playOneShotSound(url: string, volumeScale?: number): void;
    private adjustModalLayer;
    checkPopups(): void;
    private __elementTouchBegin;
}
