import { GComponent } from "./GComponent";
import { GTree } from "./GTree";
export declare class GTreeNode {
    data?: any;
    private _parent;
    private _children;
    private _expanded;
    private _level;
    private _indentLevel;
    private _addIndent?;
    private _tree;
    private _cell;
    private _indentObj;
    private _resURL?;
    private _leafController;
    private _isFolder;
    onExpanded?: (expand: boolean) => void;
    constructor(isFolder?: boolean, resURL?: string, addIndent?: number);
    set expanded(value: boolean);
    get expanded(): boolean;
    get isFolder(): boolean;
    set isFolder(value: boolean);
    get parent(): GTreeNode;
    get text(): string;
    set text(value: string);
    get icon(): string;
    set icon(value: string);
    get cell(): GComponent;
    set cell(value: GComponent);
    createCell(): void;
    get level(): number;
    addChild(child: GTreeNode): GTreeNode;
    addChildAt(child: GTreeNode, index: number): GTreeNode;
    removeChild(child: GTreeNode): GTreeNode;
    removeChildAt(index: number): GTreeNode;
    removeChildren(beginIndex?: number, endIndex?: number): void;
    getChildAt(index: number): GTreeNode;
    getChildIndex(child: GTreeNode): number;
    getPrevSibling(): GTreeNode;
    getNextSibling(): GTreeNode;
    setChildIndex(child: GTreeNode, index: number): void;
    swapChildren(child1: GTreeNode, child2: GTreeNode): void;
    swapChildrenAt(index1: number, index2: number): void;
    get numChildren(): number;
    getChildren(): ReadonlyArray<GTreeNode>;
    expandToRoot(): void;
    get tree(): GTree;
    _setTree(value: GTree): void;
    private __expandedStateChanged;
    private __cellMouseDown;
    private __clickExpandButton;
}
