import { Event } from "../event/Event";
import { ByteBuffer } from "../utils/ByteBuffer";
import { GComponent } from "./GComponent";
import { GList } from "./GList";
import { GObject } from "./GObject";
import { GTreeNode } from "./GTreeNode";
export declare class GTree extends GList {
    treeNodeRender: (node: GTreeNode, obj: GComponent) => void;
    treeNodeWillExpand: (node: GTreeNode, expanded: boolean) => void;
    private _indent;
    private _clickToExpand;
    private _rootNode;
    constructor();
    get rootNode(): GTreeNode;
    get indent(): number;
    set indent(value: number);
    get clickToExpand(): number;
    set clickToExpand(value: number);
    getSelectedNode(): GTreeNode;
    getSelectedNodes(result?: Array<GTreeNode>): Array<GTreeNode>;
    selectNode(node: GTreeNode, scrollItToView?: boolean): void;
    unselectNode(node: GTreeNode): void;
    expandAll(folderNode?: GTreeNode): void;
    collapseAll(folderNode?: GTreeNode): void;
    private createCell;
    private getInsertIndexForNode;
    private getFolderEndIndex;
    private checkChildren;
    private hideFolderNode;
    private removeNode;
    protected dispatchItemEvent(item: GObject, evt: Event): void;
    setup_beforeAdd(buffer: ByteBuffer, beginPos: number): void;
    protected readItems(buffer: ByteBuffer): void;
}
